Moved all config data from config files to a DB collection named
DSCUAIC/schedule-backend pull request #31
Opened 2020-04-11 13:42 UTC by adriangotca98

Note: in config files need to be only PORT and DB_URI

2020-04-11 13:45 UTC, adriangotca98 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Secret storing in the database](https://trello.com/c/NI5PiwKE/24-secret-storing-in-the-database)

2020-04-12 09:06 UTC, procateodor requested changes
Hai ca schema sa fie doar `name` si `key`.
Iar cand luam secrets luat tot din db apoi le mapam pe config dupa nume si key.
De ex: config[cfg.name] = cfg.secret

2020-04-12 19:06 UTC, adriangotca98 commented
Failed tests due to env variables from heroku

2020-04-14 12:08 UTC, procateodor submitted a review, later dismissed
Să-mi zici ce trebuie pus in heroku

2020-04-14 12:17 UTC, adriangotca98 commented
> Să-mi zici ce trebuie pus in heroku

Pai ti-am trimis pe slack fisierele de config pentru heroku, alea nu au SECRET_KEY care trebuie pt cheile de pe DB

2020-04-14 18:15 UTC, procateodor approved these changes

2020-04-14 18:17 UTC, merged