Update user PATCH route
DSCUAIC/schedule-backend pull request #35
Opened 2020-04-15 12:05 UTC by andra5980

2020-04-15 13:17 UTC, procateodor commented on controllers/userController.js
> +    const idToSearchFor = mongoose.Types.ObjectId(req.user['user:id'])
We have a constant for that in `constants` folder

2020-04-15 13:18 UTC, procateodor approved these changes
One small comment.

2020-04-21 07:27 UTC, procateodor requested changes
Kind reminder.

2020-04-21 18:50 UTC, adriangotca98 requested changes

2020-04-21 18:50 UTC, adriangotca98 commented on controllers/userController.js
> +    })
Add a message with this please

2020-04-21 18:50 UTC, adriangotca98 commented on controllers/userController.js
>      return res.status(HttpStatus.INTERNAL_SERVER_ERROR).json({
Here a message please

2020-04-24 17:14 UTC, procateodor commented
![](https://github.trello.services/images/mini-trello-icon.png) [Update user data route](https://trello.com/c/vhTsCDYb/18-update-user-data-route)

2020-04-24 17:21 UTC, procateodor submitted a review, later dismissed
LGTM

2020-04-28 16:57 UTC, adriangotca98 requested changes

2020-04-28 16:57 UTC, adriangotca98 commented on controllers/userController.js
>      return res.status(HttpStatus.INTERNAL_SERVER_ERROR).json({
on the 500 response, there should be a message. It wasn't visible at the time of my review, please add a message to the response. Sorry for misunderstanding this

2020-04-28 17:07 UTC, adriangotca98 approved these changes

2020-04-28 17:08 UTC, merged