Feat/inga/change profile image
DSCUAIC/schedule-backend pull request #39
Opened 2020-04-21 11:44 UTC by ingatrifan

2020-04-21 17:11 UTC, procateodor commented
![](https://github.trello.services/images/mini-trello-icon.png) [Update user profile picture](https://trello.com/c/uLRNmaYm/33-update-user-profile-picture)

2020-04-21 18:56 UTC, adriangotca98 requested changes

2020-04-21 18:56 UTC, adriangotca98 commented on server.js
> +  })
use config object here, in process.env we'll only have NODE_ENV, PORT, DB_URI and SECRET_KEY, nothing more.

2020-04-21 18:56 UTC, adriangotca98 commented on controllers/userController.js
> +    })
Add a message to this response so every 200 response have a generic template

2020-04-22 08:56 UTC, procateodor requested changes
See @adriangotca  comments.

2020-04-23 12:08 UTC, procateodor requested changes
Resolve conflicts

2020-04-24 07:49 UTC, ingatrifan commented
Am dat acum pull de pe master nu imi arata ca as avea conflicte, imi zice already up to date.

2020-04-24 10:08 UTC, procateodor submitted a review, later dismissed

2020-04-28 17:02 UTC, procateodor approved these changes

2020-04-28 19:19 UTC, adriangotca98 requested changes

2020-04-28 19:19 UTC, adriangotca98 commented on controllers/userController.js
> +    })
message and status to the 200 response, please

2020-04-28 19:19 UTC, adriangotca98 commented on server.js
> +  })
use config object, the process.env will only have PORT, NODE_ENV, DB_URI and SECRET_KEY. All other config data will be stored on the config object. Also, make sure that CLOUDINARY_API_KEY and CLOUDINARY_API_SECRET are present in the db

2020-04-29 14:40 UTC, procateodor approved these changes

2020-04-29 14:44 UTC, adriangotca98 approved these changes

2020-04-29 16:13 UTC, merged